name: Bug report
description: Report a problem with Barbossa
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A short, clear description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or output
      description: Paste any relevant logs or stack traces.
      render: shell
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide relevant environment details.
      placeholder: |
        OS:
        Python version:
        Docker version:
        Barbossa version:
  - type: textarea
    id: config
    attributes:
      label: Relevant configuration
      description: Redact secrets. Paste relevant portions of config.
      render: json
