name: Feature request
description: Suggest an idea or enhancement
title: "feat: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing an improvement.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: A clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How should Barbossa solve this?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you considered?
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, screenshots, or examples.
